import type { AgentPackFile, MCPPolicyFile, ReadinessReport, ScoreJsonExport } from './types';
import { buildDeliveryPackFiles } from './deliveryPack';
import { normalizeProjectIntake } from './intake';
import type { PartialProjectIntake } from './intake';

type ZipModule = typeof import('jszip');

export const REQUIRED_AGENT_PACK_FILES = [
  'AGENTS.md',
  'CLAUDE.md',
  'CODEX_PROMPTS.md',
  'REVIEWER_PROMPT.md',
  'SECURITY_REVIEW.md',
  'TESTING_STRATEGY.md',
  'CI_QUALITY_GATE.yml',
  'AGENT_READINESS_REPORT.md',
] as const;

export const AGENT_INSTRUCTIONS_FOLDER = '01-agent-instructions';
export const SKILLS_FOLDER = '02-skills';
export const MCP_GOVERNANCE_FOLDER = '03-mcp-governance';
export const TESTING_FOLDER = '04-testing';
export const AI_ACT_READINESS_FOLDER = '05-ai-act-readiness';
export const CLIENT_HANDOFF_FOLDER = '06-client-handoff';
export const REPO_CONTEXT_FOLDER = '07-context';

export interface BuildAgentPackZipOptions {
  repositoryName?: string;
  scoreJson?: unknown;
  intake?: PartialProjectIntake;
}

export function sanitizeRepositoryName(name: string): string {
  const cleaned = name
    .trim()
    .replace(/\.zip$/i, '')
    .replace(/[^a-z0-9._-]+/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^[-._]+|[-._]+$/g, '')
    .toLowerCase();

  return cleaned || 'repository';
}

export function buildAgentPackZipFilename(repositoryName: string): string {
  return `shipseal-delivery-pack-${sanitizeRepositoryName(repositoryName)}.zip`;
}

export function buildScoreJson(report: ReadinessReport): ScoreJsonExport {
  return {
    product: 'ShipSeal',
    generatedBy: 'Generated by ShipSeal',
    repositoryName: report.repoName,
    scanTimestamp: report.scannedAt,
    source: report.source,
    score: report.score,
    status: report.level,
    isReady: report.isReady,
    criticalBlockers: report.blockers,
    improvements: report.improvements,
    categories: report.categories,
    detectedStack: report.stack,
    scanSummary: report.scanSummary,
    aiNarrative: report.aiNarrative,
    repoContextPack: {
      repositoryName: report.repoContextPack.repositoryName,
      detectedStack: report.repoContextPack.detectedStack,
      packageManager: report.repoContextPack.packageManager,
      scriptCount: Object.keys(report.repoContextPack.scripts).length,
      keyFolders: report.repoContextPack.keyFolders,
      existingInstructionFiles: report.repoContextPack.existingInstructionFiles,
      blockerCount: report.repoContextPack.blockers.length,
      ignoredFolders: report.repoContextPack.ignoredFolders,
      securityFindingCount: report.repoContextPack.securityFindings.length,
      mcpStatus: report.repoContextPack.mcpSummary.status,
      rawFileContentsIncluded: false,
    },
    generatedFiles: report.agentPack.map(file => file.name),
    mcpReadiness: {
      score: report.mcpReadiness.score,
      status: report.mcpReadiness.status,
      summary: report.mcpReadiness.summary,
      aiNarrative: report.mcpReadiness.aiNarrative,
      recommendedServerCategories: report.mcpReadiness.recommendedServerCategories,
      riskFindings: report.mcpReadiness.riskFindings,
      generatedFiles: report.mcpReadiness.generatedFiles.map(file => file.filename),
    },
  };
}

export function downloadTextFile(filename: string, content: string, type = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function downloadJsonFile(filename: string, value: unknown) {
  downloadTextFile(filename, `${JSON.stringify(value, null, 2)}\n`, 'application/json;charset=utf-8');
}

export function buildRepoContextPackJson(report: ReadinessReport) {
  return report.repoContextPack;
}

export async function buildAgentPackZipBlob(
  files: AgentPackFile[],
  mcpFiles: MCPPolicyFile[] = [],
  contextFiles?: { markdown: string; json: unknown },
  options: BuildAgentPackZipOptions = {}
): Promise<Blob> {
  const JSZip = (await import('jszip') as ZipModule).default;
  const zip = new JSZip();
  const deliveryFiles = buildDeliveryPackFiles({
    agentFiles: files,
    mcpFiles,
    contextFiles,
    repositoryName: options.repositoryName,
    scoreJson: options.scoreJson,
    intake: options.intake,
  });

  for (const file of deliveryFiles) {
    zip.file(file.path, file.content);
  }

  return zip.generateAsync({ type: 'blob' });
}

export async function downloadAgentPackZip(
  repositoryName: string,
  files: AgentPackFile[],
  mcpFiles: MCPPolicyFile[] = [],
  contextFiles?: { markdown: string; json: unknown },
  scoreJson?: unknown,
  intake?: PartialProjectIntake
) {
  const normalizedIntake = normalizeProjectIntake(intake, repositoryName);
  const blob = await buildAgentPackZipBlob(files, mcpFiles, contextFiles, { repositoryName, scoreJson, intake: normalizedIntake });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = buildAgentPackZipFilename(normalizedIntake.projectName);
  link.click();
  URL.revokeObjectURL(url);
}
