import { describe, expect, it, vi } from 'vitest';
import handler from '../../api/create-readiness-pr';
import {
  createReadinessPrOnGitHub,
  validateCreateReadinessPrRequest,
} from '../../api/_lib/githubWrite';
import { buildSampleReport } from '@/lib/readiness';
import { buildCreateReadinessPrPayload } from '@/lib/github/write';

const files = [
  { path: 'AGENTS.md', content: 'Generated by ShipSeal\n\nAgent instructions.' },
  { path: 'CLAUDE.md', content: 'Generated by ShipSeal\n\nClaude instructions.' },
  { path: '.github/workflows/ci.yml', content: '# Generated by ShipSeal\nname: ShipSeal Readiness CI' },
];

const validPayload = {
  owner: 'Csisz',
  repo: 'shipseal',
  baseBranch: 'main',
  branchName: 'shipseal/readiness-pack',
  prTitle: 'Add ShipSeal readiness and agent governance pack',
  prBody: 'This pull request adds ShipSeal-generated readiness files.',
  files,
  githubToken: 'ghp_mock',
};

function jsonResponse(body: unknown, status = 200) {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
  } as Response;
}

function createResponse() {
  return {
    statusCode: 0,
    body: '',
    setHeader: vi.fn(),
    end(value: string) {
      this.body = value;
    },
    json() {
      return JSON.parse(this.body);
    },
  };
}

describe('Create Readiness PR API', () => {
  it('validates missing token, missing files, invalid repo and forbidden branch names', () => {
    expect(validateCreateReadinessPrRequest({ ...validPayload, githubToken: '' }))
      .toEqual({ status: 401, error: 'GitHub token is required.' });
    expect(validateCreateReadinessPrRequest({ ...validPayload, files: [] }))
      .toEqual({ status: 400, error: 'Readiness Fix Pack files are required.' });
    expect(validateCreateReadinessPrRequest({ ...validPayload, owner: 'bad owner' }))
      .toEqual({ status: 400, error: 'Invalid GitHub owner.' });
    expect(validateCreateReadinessPrRequest({ ...validPayload, branchName: 'main' }))
      .toEqual({ status: 400, error: 'ShipSeal will not write directly to main or master.' });
    expect(validateCreateReadinessPrRequest({ ...validPayload, branchName: 'master' }))
      .toEqual({ status: 400, error: 'ShipSeal will not write directly to main or master.' });
  });

  it('builds a PR payload from the Readiness Fix Pack files', () => {
    const report = {
      ...buildSampleReport(),
      source: {
        sourceType: 'github-url' as const,
        githubOwner: 'Csisz',
        githubRepo: 'shipseal',
        githubBranch: 'main',
        sourceUrl: 'https://github.com/Csisz/shipseal',
      },
    };
    const payload = buildCreateReadinessPrPayload({ report, githubToken: 'ghp_mock' });
    const paths = payload.files.map(file => file.path);

    expect(payload.owner).toBe('Csisz');
    expect(payload.repo).toBe('shipseal');
    expect(paths).toContain('AGENTS.md');
    expect(paths).toContain('CLAUDE.md');
    expect(paths).toContain('.github/workflows/ci.yml');
  });

  it('infers owner and repo from owner/repo repository names and honors default branch metadata', () => {
    const report = {
      ...buildSampleReport(),
      repoName: 'Csisz/shipseal',
      source: {
        sourceType: 'github-url' as const,
        githubDefaultBranch: 'develop',
      },
    };

    const payload = buildCreateReadinessPrPayload({ report, githubToken: 'ghp_mock' });

    expect(payload.owner).toBe('Csisz');
    expect(payload.repo).toBe('shipseal');
    expect(payload.baseBranch).toBe('develop');
  });

  it('leaves base branch unset when GitHub metadata does not include a branch', () => {
    const report = {
      ...buildSampleReport(),
      source: {
        sourceType: 'github-url' as const,
        githubOwner: 'Csisz',
        githubRepo: 'shipseal',
        sourceUrl: 'https://github.com/Csisz/shipseal',
      },
    };

    const payload = buildCreateReadinessPrPayload({ report, githubToken: 'ghp_mock' });

    expect(payload.baseBranch).toBeUndefined();
  });

  it('creates a branch, uploads files, and opens a pull request with mocked GitHub calls', async () => {
    const calls: string[] = [];
    const fetchMock = vi.fn(async (url: string, init?: RequestInit) => {
      calls.push(`${init?.method || 'GET'} ${url}`);
      if (url.endsWith('/repos/Csisz/shipseal/git/ref/heads/main')) {
        return jsonResponse({ object: { sha: 'base-sha' } });
      }
      if (url.endsWith('/repos/Csisz/shipseal/git/refs')) {
        return jsonResponse({ ref: 'refs/heads/shipseal/readiness-pack' }, 201);
      }
      if (url.includes('/contents/')) {
        if ((init?.method || 'GET') === 'GET') return jsonResponse({}, 404);
        return jsonResponse({ content: { path: 'file' } }, 201);
      }
      if (url.endsWith('/repos/Csisz/shipseal/pulls')) {
        return jsonResponse({ html_url: 'https://github.com/Csisz/shipseal/pull/12' }, 201);
      }
      return jsonResponse({}, 200);
    });

    const result = await createReadinessPrOnGitHub(validPayload, { fetcher: fetchMock as never });

    expect(result).toEqual({
      pullRequestUrl: 'https://github.com/Csisz/shipseal/pull/12',
      branchName: 'shipseal/readiness-pack',
      baseBranch: 'main',
      fileCount: 3,
    });
    expect(calls.some(call => call.includes('/git/refs'))).toBe(true);
    expect(calls.some(call => call.includes('/pulls'))).toBe(true);
    expect(fetchMock.mock.calls.every(([, init]) => String(init?.headers?.['Authorization' as never] || '').includes('ghp_mock'))).toBe(true);
  });

  it('uses a timestamped branch when the default readiness branch already exists', async () => {
    const fetchMock = vi.fn(async (url: string, init?: RequestInit) => {
      if (url.endsWith('/repos/Csisz/shipseal/git/ref/heads/main')) {
        return jsonResponse({ object: { sha: 'base-sha' } });
      }
      if (url.endsWith('/repos/Csisz/shipseal/git/refs')) {
        const body = JSON.parse(String(init?.body || '{}'));
        if (body.ref === 'refs/heads/shipseal/readiness-pack') {
          return jsonResponse({ message: 'Reference already exists' }, 422);
        }
        return jsonResponse({ ref: body.ref }, 201);
      }
      if (url.includes('/contents/')) {
        if ((init?.method || 'GET') === 'GET') return jsonResponse({}, 404);
        return jsonResponse({}, 201);
      }
      if (url.endsWith('/repos/Csisz/shipseal/pulls')) {
        return jsonResponse({ html_url: 'https://github.com/Csisz/shipseal/pull/13' }, 201);
      }
      return jsonResponse({}, 200);
    });

    const result = await createReadinessPrOnGitHub(validPayload, {
      fetcher: fetchMock as never,
      now: () => new Date(Date.UTC(2026, 5, 4, 9, 30)),
    });

    expect(result.branchName).toBe('shipseal/readiness-pack-20260604-0930');
  });

  it('handler rejects missing token without leaking token data', async () => {
    const req = { method: 'POST', body: { ...validPayload, githubToken: '' } };
    const res = createResponse();

    await handler(req as never, res as never);

    expect(res.statusCode).toBe(401);
    expect(res.json()).toEqual({ error: 'GitHub token is required.' });
    expect(res.body).not.toContain('ghp_mock');
  });
});
