import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { buildSampleReport } from '@/lib/readiness';
import {
  buildAgentPackZipBlob,
  buildAgentPackZipFilename,
  buildRepoContextPackJson,
  buildScoreJson,
} from '@/lib/exports';
import { getDeliveryPackRequiredPaths, resolveDeliveryPackFocus } from '@/lib/deliveryPack';

async function zipText(zip: JSZip, path: string): Promise<string> {
  const file = zip.file(path);
  expect(file).toBeTruthy();
  return file?.async('string') || '';
}

describe('ShipSeal Delivery Pack ZIP export', () => {
  it('uses the ShipSeal Delivery Pack filename', () => {
    expect(buildAgentPackZipFilename('Client Project.zip')).toBe('shipseal-delivery-pack-client-project.zip');
    expect(buildAgentPackZipFilename('...')).toBe('shipseal-delivery-pack-repository.zip');
  });

  it('exports every manifest path into the ZIP', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of getDeliveryPackRequiredPaths()) {
      expect(zip.file(path), path).toBeTruthy();
    }
  });

  it('exports valid score.json with ShipSeal metadata', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);
    const scoreJson = JSON.parse(await zipText(zip, 'score.json'));

    expect(scoreJson.product).toBe('ShipSeal');
    expect(scoreJson.projectName).toBe(report.repoName);
    expect(scoreJson.generatedBy).toBe('Generated by ShipSeal');
    expect(scoreJson.selectedPackage).toBe('Full ShipSeal package');
    expect(scoreJson.outputCount).toBe(getDeliveryPackRequiredPaths().length);
    expect(scoreJson.content.repositoryName).toBe(report.repoName);
    expect(scoreJson.content.outputCount).toBe(getDeliveryPackRequiredPaths().length);
    expect(scoreJson.content.generatedFiles).toEqual(getDeliveryPackRequiredPaths());
  });

  it('maps selected goals to focused Delivery Pack outputs', () => {
    const clientHandoff = resolveDeliveryPackFocus(['client-handoff']);
    const testing = resolveDeliveryPackFocus(['testing-red-team']);
    const full = resolveDeliveryPackFocus(['full-package']);

    expect(clientHandoff.generatedPaths).toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
    expect(clientHandoff.generatedPaths).toContain('06-client-handoff/EXECUTIVE_SUMMARY.md');
    expect(clientHandoff.generatedPaths).not.toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(testing.generatedPaths).toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(testing.generatedPaths).toContain('04-testing/CI_QUALITY_GATE.yml');
    expect(testing.generatedPaths).not.toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
    expect(full.generatedPaths).toEqual(getDeliveryPackRequiredPaths());
  });

  it('includes selected goal focus metadata in score.json', () => {
    const report = buildSampleReport();
    const scoreJson = buildScoreJson(report, { selectedPackages: ['mcp-readiness'] });
    const focus = resolveDeliveryPackFocus(['mcp-readiness']);

    expect(scoreJson.generatedFiles).toEqual(focus.generatedPaths);
    expect(scoreJson.outputCount).toBe(focus.generatedPaths.length);
    expect(scoreJson.deliveryPackFocus?.fullPackage).toBe(false);
    expect(scoreJson.deliveryPackFocus?.packageLabel).toBe('MCP readiness pack');
    expect(scoreJson.deliveryPackFocus?.selectedGoals).toEqual([{
      id: 'mcp-readiness',
      title: 'MCP readiness and tool integration',
    }]);
    expect(scoreJson.deliveryPackFocus?.generatedFiles).toEqual(focus.generatedPaths);
    expect(scoreJson.deliveryPackFocus?.outputCount).toBe(focus.generatedPaths.length);
    expect(scoreJson.deliveryPackFocus?.manifestFiles).toEqual(getDeliveryPackRequiredPaths());
    expect(scoreJson.deliveryPackFocus?.manifestOutputCount).toBe(getDeliveryPackRequiredPaths().length);
    expect(scoreJson.deliveryPackFocus?.emphasizedFiles).toContain('03-mcp-governance/MCP_READINESS.md');
    expect(scoreJson.deliveryPackFocus?.emphasizedFiles).not.toContain('04-testing/EVAL_TEST_CASES.md');
  });

  it('keeps score.json metadata and focused ZIP file list consistent', async () => {
    const report = buildSampleReport();
    const selectedPackages = ['client-handoff'];
    const scoreJson = buildScoreJson(report, { selectedPackages });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name).sort();
    const exportedScoreJson = JSON.parse(await zipText(zip, 'score.json'));

    expect(scoreJson.deliveryPackFocus?.packageLabel).toBe('Client handoff pack');
    expect(scoreJson.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(scoreJson.deliveryPackFocus?.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(paths).toEqual([...scoreJson.generatedFiles].sort());
    expect(exportedScoreJson.selectedPackage).toBe(scoreJson.deliveryPackFocus?.packageLabel);
    expect(exportedScoreJson.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(exportedScoreJson.content.generatedFiles).toEqual(scoreJson.generatedFiles);
  });

  it('exports a focused ZIP whose file list matches score.json generatedFiles', async () => {
    const report = buildSampleReport();
    const selectedPackages = ['testing-red-team'];
    const scoreJson = buildScoreJson(report, { selectedPackages });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name).sort();

    expect(paths).toEqual([...scoreJson.generatedFiles].sort());
    expect(paths).toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(paths).toContain('score.json');
    expect(paths).not.toContain('03-mcp-governance/MCP_READINESS.md');
    expect(paths).not.toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
  });

  it('includes at least five SKILL.md files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);
    const skillPaths = getDeliveryPackRequiredPaths().filter(path => path.endsWith('/SKILL.md'));

    expect(skillPaths.length).toBeGreaterThanOrEqual(5);
    for (const path of skillPaths) {
      const content = await zipText(zip, path);
      expect(content.trim()).toContain('Generated by ShipSeal');
      expect(content.trim()).toContain(report.repoName);
    }
  });

  it('exports non-empty eval, red-team, and client handoff files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of [
      '04-testing/EVAL_TEST_CASES.md',
      '04-testing/RED_TEAM_PROMPTS.md',
      '06-client-handoff/CLIENT_HANDOFF_REPORT.md',
    ]) {
      const content = await zipText(zip, path);
      expect(content.trim().length).toBeGreaterThan(80);
      expect(content).toContain('ShipSeal');
      expect(content).toContain(report.repoName);
      expect(content).toContain('Generated by ShipSeal');
    }
  });
});
