import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { buildSampleReport } from '@/lib/readiness';
import {
  buildAgentPackZipBlob,
  buildAgentPackZipFilename,
  buildRepoContextPackJson,
  buildScoreJson,
} from '@/lib/exports';
import { getDeliveryPackRequiredPaths } from '@/lib/deliveryPack';

async function zipText(zip: JSZip, path: string): Promise<string> {
  const file = zip.file(path);
  expect(file).toBeTruthy();
  return file?.async('string') || '';
}

describe('ShipSeal Delivery Pack ZIP export', () => {
  it('uses the ShipSeal Delivery Pack filename', () => {
    expect(buildAgentPackZipFilename('Client Project.zip')).toBe('shipseal-delivery-pack-client-project.zip');
    expect(buildAgentPackZipFilename('...')).toBe('shipseal-delivery-pack-repository.zip');
  });

  it('exports every manifest path into the ZIP', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of getDeliveryPackRequiredPaths()) {
      expect(zip.file(path), path).toBeTruthy();
    }
  });

  it('exports valid score.json with ShipSeal metadata', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);
    const scoreJson = JSON.parse(await zipText(zip, 'score.json'));

    expect(scoreJson.product).toBe('ShipSeal');
    expect(scoreJson.projectName).toBe(report.repoName);
    expect(scoreJson.generatedBy).toBe('Generated by ShipSeal');
    expect(scoreJson.content.repositoryName).toBe(report.repoName);
  });

  it('includes at least five SKILL.md files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);
    const skillPaths = getDeliveryPackRequiredPaths().filter(path => path.endsWith('/SKILL.md'));

    expect(skillPaths.length).toBeGreaterThanOrEqual(5);
    for (const path of skillPaths) {
      const content = await zipText(zip, path);
      expect(content.trim()).toContain('Generated by ShipSeal');
      expect(content.trim()).toContain(report.repoName);
    }
  });

  it('exports non-empty eval, red-team, and client handoff files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of [
      '04-testing/EVAL_TEST_CASES.md',
      '04-testing/RED_TEAM_PROMPTS.md',
      '06-client-handoff/CLIENT_HANDOFF_REPORT.md',
    ]) {
      const content = await zipText(zip, path);
      expect(content.trim().length).toBeGreaterThan(80);
      expect(content).toContain('ShipSeal');
      expect(content).toContain(report.repoName);
      expect(content).toContain('Generated by ShipSeal');
    }
  });
});
