import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { buildSampleReport } from '@/lib/readiness';
import {
  buildAgentPackZipBlob,
  buildAgentPackZipFilename,
  buildRepoContextPackJson,
  buildScoreJson,
} from '@/lib/exports';
import { getDeliveryPackRequiredPaths, resolveDeliveryPackFocus } from '@/lib/deliveryPack';
import { applyAgentOperatingModeToFiles } from '@/lib/agentOperatingMode';
import { getFolderAgentSuggestionPaths } from '@/lib/deliveryPack/folderAgents';

async function zipText(zip: JSZip, path: string): Promise<string> {
  const file = zip.file(path);
  expect(file).toBeTruthy();
  return file?.async('string') || '';
}

describe('ShipSeal Delivery Pack ZIP export', () => {
  it('uses the ShipSeal Delivery Pack filename', () => {
    expect(buildAgentPackZipFilename('Client Project.zip')).toBe('shipseal-delivery-pack-client-project.zip');
    expect(buildAgentPackZipFilename('...')).toBe('shipseal-delivery-pack-repository.zip');
  });

  it('exports every manifest path into the ZIP', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of getDeliveryPackRequiredPaths()) {
      expect(zip.file(path), path).toBeTruthy();
    }
  });

  it('exports valid score.json with ShipSeal metadata', async () => {
    const report = buildSampleReport();
    const expectedScoreJson = buildScoreJson(report);
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: expectedScoreJson }
    );
    const zip = await JSZip.loadAsync(blob);
    const scoreJson = JSON.parse(await zipText(zip, 'score.json'));

    expect(scoreJson.product).toBe('ShipSeal');
    expect(scoreJson.projectName).toBe(report.repoName);
    expect(scoreJson.generatedBy).toBe('Generated by ShipSeal');
    expect(scoreJson.selectedPackage).toBe('Full ShipSeal package');
    expect(scoreJson.outputCount).toBe(expectedScoreJson.generatedFiles.length);
    expect(scoreJson.content.repositoryName).toBe(report.repoName);
    expect(scoreJson.content.outputCount).toBe(expectedScoreJson.generatedFiles.length);
    expect(scoreJson.content.generatedFiles).toEqual(expectedScoreJson.generatedFiles);
    expect(scoreJson.content.generatedFiles).toContain('07-context/folder-agents/root/AGENTS.md');
  });

  it('exports Repository Health as a dedicated manifest v2 Delivery Pack artifact', async () => {
    const report = buildSampleReport();
    const expectedScoreJson = buildScoreJson(report);
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      {
        repositoryName: report.repoName,
        scoreJson: {
          ...expectedScoreJson,
          repositoryHealth: {
            ...expectedScoreJson.repositoryHealth,
            overall: {
              score: 1,
              status: 'Blocked',
              confidence: 'Low',
            },
          },
        },
        repositoryHealth: report.repositoryHealth,
      }
    );
    const zip = await JSZip.loadAsync(blob);
    const repositoryHealth = await zipText(zip, '07-context/REPOSITORY_HEALTH.md');
    const manifest = await zipText(zip, '06-client-handoff/DELIVERY_MANIFEST.md');

    expect(expectedScoreJson.generatedFiles).toContain('07-context/REPOSITORY_HEALTH.md');
    expect(expectedScoreJson.deliveryPackManifest).toMatchObject({
      schemaVersion: 2,
      repositoryHealthFile: '07-context/REPOSITORY_HEALTH.md',
      repositoryHealthScore: report.repositoryHealth.overall.score,
      repositoryHealthStatus: report.repositoryHealth.overall.status,
      repositoryHealthConfidence: report.repositoryHealth.overall.confidence,
      contextWasteRiskScore: report.repositoryHealth.dimensions.contextWaste.riskScore,
      deliveryVerificationReadinessScore: report.score,
      deliveryVerificationReadinessStatus: report.level,
    });
    expect(repositoryHealth).toContain('# Repository Health - sample-nextjs-app');
    expect(repositoryHealth).toContain(`- Project name: ${report.repoName}`);
    expect(repositoryHealth).toContain(`- Repository owner/name: ${report.repoName}`);
    expect(repositoryHealth).toContain('- Branch or ref: default ref');
    expect(repositoryHealth).toContain(`- Scan timestamp: ${report.scannedAt}`);
    expect(repositoryHealth).toContain(`- Repository Health model version: ${report.repositoryHealth.modelVersion}`);
    expect(repositoryHealth).toContain(`- Measurement method: ${report.repositoryHealth.measurementMethod}`);
    expect(repositoryHealth).toContain('Repository Health reflects the scanned repository before ShipSeal-generated improvements are applied.');
    expect(repositoryHealth).toContain(`- Score: ${report.repositoryHealth.overall.score}/100`);
    expect(repositoryHealth).toContain(`- Status: ${report.repositoryHealth.overall.status}`);
    expect(repositoryHealth).toContain('## Top Repository Improvements');
    expect(repositoryHealth).not.toContain('- Score: 1/100');
    expect(manifest).toContain('Manifest schema version: 2');
    expect(manifest).toContain('Repository Health file: 07-context/REPOSITORY_HEALTH.md');
    expect(manifest).toContain(`Repository Health: ${report.repositoryHealth.overall.score}/100`);
    expect(manifest).toContain(`Context Waste Risk: ${report.repositoryHealth.dimensions.contextWaste.riskScore}/100`);
    expect(manifest).toContain(`Delivery and verification readiness score: ${report.score}/100`);
  });

  it('maps selected goals to focused Delivery Pack outputs', () => {
    const clientHandoff = resolveDeliveryPackFocus(['client-handoff']);
    const testing = resolveDeliveryPackFocus(['testing-red-team']);
    const full = resolveDeliveryPackFocus(['full-package']);

    expect(clientHandoff.generatedPaths).toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
    expect(clientHandoff.generatedPaths).toContain('06-client-handoff/EXECUTIVE_SUMMARY.md');
    expect(clientHandoff.generatedPaths).toContain('06-client-handoff/DELIVERY_MANIFEST.md');
    expect(clientHandoff.generatedPaths).not.toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(testing.generatedPaths).toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(testing.generatedPaths).toContain('04-testing/CI_QUALITY_GATE.yml');
    expect(testing.generatedPaths).not.toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
    expect(resolveDeliveryPackFocus(['safety-risk']).generatedPaths).toContain('08-security-data/DATA_PRIVACY_CHECKLIST.md');
    expect(resolveDeliveryPackFocus(['ai-act-transparency']).generatedPaths).toContain('05-ai-act-readiness/USER_FACING_DISCLOSURE_NOTES.md');
    expect(full.generatedPaths).toEqual(getDeliveryPackRequiredPaths());
  });

  it('returns expected output paths for each major package', () => {
    const expected: Array<[string, string[]]> = [
      ['client-handoff', ['06-client-handoff/CLIENT_HANDOFF_REPORT.md', '06-client-handoff/DELIVERY_MANIFEST.md']],
      ['agent-readiness', [
        '01-agent-instructions/AGENTS.md',
        '01-agent-instructions/AGENT_COST_OPTIMIZATION.md',
        '01-agent-instructions/CURSOR_RULES.md',
        '07-context/REPO_CONTEXT_PACK.md',
        '07-context/ARCHITECTURE.md',
        '07-context/CRITICAL_FILES.md',
        '07-context/COMMAND_MAP.md',
        '07-context/KNOWN_RISKS.md',
        '07-context/TASK_ROUTER.md',
        '07-context/GLOBAL_CONTEXT.md',
        '07-context/QA_CONTEXT.md',
        '07-context/SECURITY_CONTEXT.md',
        '07-context/DOCS_CONTEXT.md',
        '07-context/MCP_CONTEXT.md',
        '07-context/SKILL_RECOMMENDATIONS.md',
        '07-context/MCP_RECOMMENDATIONS.md',
      ]],
      ['testing-red-team', ['04-testing/EVAL_TEST_CASES.md', '04-testing/CI_QUALITY_GATE.yml']],
      ['safety-risk', ['08-security-data/ENV_SECRETS_FINDINGS.md', '08-security-data/DATA_PRIVACY_CHECKLIST.md']],
      ['mcp-readiness', ['03-mcp-governance/MCP_READINESS.md', '03-mcp-governance/MCP_TOOL_ALLOWLIST.md']],
      ['ai-act-transparency', ['05-ai-act-readiness/TRANSPARENCY_NOTICE_DRAFT.md', '05-ai-act-readiness/USER_FACING_DISCLOSURE_NOTES.md']],
    ];

    for (const [packageId, paths] of expected) {
      const focus = resolveDeliveryPackFocus([packageId]);
      for (const path of paths) expect(focus.generatedPaths).toContain(path);
      expect(focus.generatedPaths).toContain('score.json');
    }
  });

  it('includes Context Compression outputs only for AI Agent Development or Full ShipSeal', () => {
    const contextCompressionPaths = [
      '07-context/ARCHITECTURE.md',
      '07-context/CRITICAL_FILES.md',
      '07-context/COMMAND_MAP.md',
      '07-context/KNOWN_RISKS.md',
      '07-context/TASK_ROUTER.md',
      '07-context/GLOBAL_CONTEXT.md',
      '07-context/QA_CONTEXT.md',
      '07-context/SECURITY_CONTEXT.md',
      '07-context/DOCS_CONTEXT.md',
      '07-context/MCP_CONTEXT.md',
      '07-context/SKILL_RECOMMENDATIONS.md',
      '07-context/MCP_RECOMMENDATIONS.md',
    ];

    for (const path of contextCompressionPaths) {
      expect(resolveDeliveryPackFocus(['agent-readiness']).generatedPaths).toContain(path);
      expect(resolveDeliveryPackFocus(['full-package']).generatedPaths).toContain(path);
      expect(resolveDeliveryPackFocus(['client-handoff']).generatedPaths).not.toContain(path);
      expect(resolveDeliveryPackFocus(['testing-red-team']).generatedPaths).not.toContain(path);
      expect(resolveDeliveryPackFocus(['safety-risk']).generatedPaths).not.toContain(path);
    }
  });

  it('includes selected goal focus metadata in score.json', () => {
    const report = buildSampleReport();
    const scoreJson = buildScoreJson(report, { selectedPackages: ['mcp-readiness'] });
    const focus = resolveDeliveryPackFocus(['mcp-readiness']);

    expect(scoreJson.generatedFiles).toEqual(focus.generatedPaths);
    expect(scoreJson.outputCount).toBe(focus.generatedPaths.length);
    expect(scoreJson.deliveryPackFocus?.fullPackage).toBe(false);
    expect(scoreJson.deliveryPackFocus?.packageLabel).toBe('MCP readiness pack');
    expect(scoreJson.deliveryPackFocus?.selectedGoals).toEqual([{
      id: 'mcp-readiness',
      title: 'MCP readiness and tool integration',
    }]);
    expect(scoreJson.deliveryPackFocus?.generatedFiles).toEqual(focus.generatedPaths);
    expect(scoreJson.deliveryPackFocus?.outputCount).toBe(focus.generatedPaths.length);
    expect(scoreJson.deliveryPackFocus?.manifestFiles).toEqual(focus.generatedPaths);
    expect(scoreJson.deliveryPackFocus?.manifestOutputCount).toBe(focus.generatedPaths.length);
    expect(scoreJson.deliveryPackFocus?.readinessPrFiles).toEqual(focus.readinessPrPaths);
    expect(scoreJson.deliveryPackFocus?.readinessPrOutputCount).toBe(focus.readinessPrPaths.length);
    expect(scoreJson.deliveryPackFocus?.emphasizedFiles).toContain('03-mcp-governance/MCP_READINESS.md');
    expect(scoreJson.deliveryPackFocus?.emphasizedFiles).not.toContain('04-testing/EVAL_TEST_CASES.md');
  });

  it('defaults score.json to Balanced Context operating mode', () => {
    const report = buildSampleReport();
    const scoreJson = buildScoreJson(report, { selectedPackages: ['agent-readiness'] });

    expect(scoreJson.agentOperatingMode).toMatchObject({
      id: 'balanced-productivity',
      label: 'Balanced Context',
      expectedTokenUsage: 'Balanced context use',
      confidence: 'Recommended default',
    });
  });

  it('exports mode-specific AI agent development outputs', async () => {
    const report = buildSampleReport();
    const folderAgentPaths = getFolderAgentSuggestionPaths(report.repoContextPack);
    const selectedPackages = ['agent-readiness'];
    const tokenSaverFiles = applyAgentOperatingModeToFiles(report, 'token-saver');
    const reliabilityFiles = applyAgentOperatingModeToFiles(report, 'maximum-reliability');
    const tokenSaverAgents = tokenSaverFiles.find(file => file.name === 'AGENTS.md')?.content || '';
    const reliabilityAgents = reliabilityFiles.find(file => file.name === 'AGENTS.md')?.content || '';
    const tokenSaverClaude = tokenSaverFiles.find(file => file.name === 'CLAUDE.md')?.content || '';
    const reliabilityClaude = reliabilityFiles.find(file => file.name === 'CLAUDE.md')?.content || '';
    const scoreJson = buildScoreJson(report, { selectedPackages, agentOperatingMode: 'token-saver' });
    const blob = await buildAgentPackZipBlob(
      tokenSaverFiles,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const costOptimization = await zipText(zip, '01-agent-instructions/AGENT_COST_OPTIMIZATION.md');
    const architecture = await zipText(zip, '07-context/ARCHITECTURE.md');
    const criticalFiles = await zipText(zip, '07-context/CRITICAL_FILES.md');
    const commandMap = await zipText(zip, '07-context/COMMAND_MAP.md');
    const knownRisks = await zipText(zip, '07-context/KNOWN_RISKS.md');
    const taskRouter = await zipText(zip, '07-context/TASK_ROUTER.md');
    const globalContext = await zipText(zip, '07-context/GLOBAL_CONTEXT.md');
    const qaContext = await zipText(zip, '07-context/QA_CONTEXT.md');
    const securityContext = await zipText(zip, '07-context/SECURITY_CONTEXT.md');
    const docsContext = await zipText(zip, '07-context/DOCS_CONTEXT.md');
    const mcpContext = await zipText(zip, '07-context/MCP_CONTEXT.md');
    const rootAgents = await zipText(zip, '07-context/folder-agents/root/AGENTS.md');
    const docsAgents = await zipText(zip, '07-context/folder-agents/docs/AGENTS.md');

    expect(tokenSaverAgents).toContain('Recommended operating mode: Focused Context');
    expect(tokenSaverAgents).not.toContain('Recommended operating mode: Balanced Context');
    expect(tokenSaverAgents).toContain('Expected context use: Lowest context use');
    expect(tokenSaverAgents).toContain('Reason: Use this for short, low-risk iterations');
    expect(tokenSaverAgents).toContain('ShipSeal helps AI coding agents avoid unnecessary context usage and excessive verification cycles');
    expect(reliabilityAgents).toContain('Recommended operating mode: Maximum Reliability');
    expect(reliabilityAgents).toContain('Expected context use: Broader context coverage');
    expect(reliabilityAgents).toContain('Run full test/build commands when the change touches shared logic');
    expect(tokenSaverAgents).not.toBe(reliabilityAgents);
    expect(tokenSaverClaude).toContain('Recommended operating mode: Focused Context');
    expect(reliabilityClaude).toContain('Recommended operating mode: Maximum Reliability');
    expect(tokenSaverClaude).not.toBe(reliabilityClaude);
    expect(scoreJson.generatedFiles).toContain('01-agent-instructions/AGENT_COST_OPTIMIZATION.md');
    expect(scoreJson.agentOperatingMode?.label).toBe('Focused Context');
    expect(scoreJson.agentOperatingMode?.expectedTokenUsage).toBe('Lowest context use');
    expect(costOptimization).toContain('Recommended operating mode: Focused Context');
    expect(costOptimization).toContain('Expected context use: Lowest context use');
    expect(costOptimization).toContain('## Expected tradeoffs');
    expect(costOptimization).toContain('Avoid full build/test unless explicitly requested');
    expect(architecture).toContain('sample-nextjs-app');
    expect(architecture).toContain('Detected Stack');
    expect(criticalFiles).toContain('Do not start by reading the whole repository.');
    expect(criticalFiles).toContain('package.json');
    expect(commandMap).toContain('test');
    expect(commandMap).toContain('build');
    expect(knownRisks).toContain('Risks below are based only on existing ShipSeal scan and readiness signals.');
    expect(taskRouter).toContain('Use this to open fewer files before making changes.');
    expect(taskRouter).toContain('Suggested folder-level AGENTS.md files are generated');
    expect(taskRouter).toContain('07-context/SECURITY_CONTEXT.md');
    expect(globalContext).toContain('sample-nextjs-app');
    expect(globalContext).toContain('Recommended operating mode');
    expect(globalContext).toContain('07-context/TASK_ROUTER.md');
    expect(qaContext).toContain('Playwright');
    expect(qaContext).toContain('Test command');
    expect(securityContext).toContain('.env.example');
    expect(securityContext).toContain('not legal advice');
    expect(docsContext).toContain('docs/architecture.md');
    expect(mcpContext).toContain('Recommended MCP tools');
    expect(mcpContext).toContain('read-only MCP access');
    expect(rootAgents).toContain('Suggested folder-level AGENTS.md files. Review before copying into your repository.');
    expect(rootAgents).toContain('Do not start by reading the whole repository.');
    expect(rootAgents).toContain('07-context/ARCHITECTURE.md');
    expect(rootAgents).toContain('07-context/TASK_ROUTER.md');
    expect(docsAgents).toContain('Do not reintroduce deprecated founder-review positioning');
    expect(scoreJson.generatedFiles).toEqual(resolveDeliveryPackFocus(selectedPackages, { folderAgentPaths }).generatedPaths);
    expect(scoreJson.generatedFiles).toContain('07-context/folder-agents/root/AGENTS.md');
  });

  it('generates folder-level AGENTS suggestions only for detected folders in agent packages', async () => {
    const report = buildSampleReport();
    const folderAgentPaths = getFolderAgentSuggestionPaths(report.repoContextPack);

    expect(folderAgentPaths).toContain('07-context/folder-agents/root/AGENTS.md');
    expect(folderAgentPaths).toContain('07-context/folder-agents/docs/AGENTS.md');
    expect(folderAgentPaths).not.toContain('07-context/folder-agents/src/components/AGENTS.md');

    const agentScoreJson = buildScoreJson(report, { selectedPackages: ['agent-readiness'] });
    const clientScoreJson = buildScoreJson(report, { selectedPackages: ['client-handoff'] });
    const fullScoreJson = buildScoreJson(report, { selectedPackages: ['full-package'] });

    expect(agentScoreJson.generatedFiles).toContain('07-context/folder-agents/root/AGENTS.md');
    expect(fullScoreJson.generatedFiles).toContain('07-context/folder-agents/root/AGENTS.md');
    expect(clientScoreJson.generatedFiles).not.toContain('07-context/folder-agents/root/AGENTS.md');
    expect(agentScoreJson.outputCount).toBe(agentScoreJson.generatedFiles.length);
    expect(agentScoreJson.deliveryPackFocus?.manifestOutputCount).toBe(agentScoreJson.generatedFiles.length);
    expect(agentScoreJson.specializedContextPacks).toEqual({
      generated: true,
      files: [
        '07-context/GLOBAL_CONTEXT.md',
        '07-context/QA_CONTEXT.md',
        '07-context/SECURITY_CONTEXT.md',
        '07-context/DOCS_CONTEXT.md',
        '07-context/MCP_CONTEXT.md',
      ],
      outputCount: 5,
    });
    expect(clientScoreJson.specializedContextPacks?.generated).toBe(false);

    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: agentScoreJson, selectedPackages: ['agent-readiness'] }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name);

    expect(paths).toContain('07-context/folder-agents/root/AGENTS.md');
    expect(paths).toContain('07-context/folder-agents/docs/AGENTS.md');
    expect(paths).not.toContain('07-context/folder-agents/src/components/AGENTS.md');
    expect(paths.sort()).toEqual([...agentScoreJson.generatedFiles].sort());
  });

  it('keeps score.json metadata and focused ZIP file list consistent', async () => {
    const report = buildSampleReport();
    const selectedPackages = ['client-handoff'];
    const scoreJson = buildScoreJson(report, { selectedPackages });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name).sort();
    const exportedScoreJson = JSON.parse(await zipText(zip, 'score.json'));

    expect(scoreJson.deliveryPackFocus?.packageLabel).toBe('Client handoff pack');
    expect(scoreJson.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(scoreJson.deliveryPackFocus?.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(paths).toEqual([...scoreJson.generatedFiles].sort());
    expect(exportedScoreJson.selectedPackage).toBe(scoreJson.deliveryPackFocus?.packageLabel);
    expect(exportedScoreJson.outputCount).toBe(scoreJson.generatedFiles.length);
    expect(exportedScoreJson.content.generatedFiles).toEqual(scoreJson.generatedFiles);
    expect(exportedScoreJson.content.deliveryPackFocus.manifestOutputCount).toBe(scoreJson.generatedFiles.length);
  });

  it('keeps the delivery manifest aligned with score.json metadata and generated files', async () => {
    const report = buildSampleReport();
    const selectedPackages = ['client-handoff'];
    const scoreJson = buildScoreJson(report, { selectedPackages });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const manifest = await zipText(zip, '06-client-handoff/DELIVERY_MANIFEST.md');

    expect(manifest).toContain(`Repository: ${scoreJson.repositoryName}`);
    expect(manifest).toContain('Branch / ref:');
    expect(manifest).toContain(`Selected package: ${scoreJson.deliveryPackFocus?.packageLabel}`);
    expect(manifest).toContain(`Output count: ${scoreJson.outputCount}`);
    expect(manifest).toContain(`Delivery and verification readiness score: ${scoreJson.score}/100`);
    expect(manifest).toContain(`Delivery and verification readiness status: ${scoreJson.status}`);
    expect(manifest).toContain(`Repository Health: ${scoreJson.repositoryHealth.overall.score}/100`);
    expect(manifest).toContain(`Repository Health status: ${scoreJson.repositoryHealth.overall.status}`);
    expect(manifest).toContain(`Context Waste Risk: ${scoreJson.repositoryHealth.dimensions.contextWaste.riskScore}/100`);
    expect(manifest).toContain('07-context/REPOSITORY_HEALTH.md');
    expect(manifest).toContain('## Scan Evidence');
    expect(manifest).toContain('Code execution: ShipSeal did not execute repository code.');
    for (const path of scoreJson.generatedFiles) {
      expect(manifest).toContain(`- ${path}`);
    }
  });

  it('exports a focused ZIP whose file list matches score.json generatedFiles', async () => {
    const report = buildSampleReport();
    const selectedPackages = ['testing-red-team'];
    const scoreJson = buildScoreJson(report, { selectedPackages });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name).sort();

    expect(paths).toEqual([...scoreJson.generatedFiles].sort());
    expect(paths).toContain('04-testing/RED_TEAM_PROMPTS.md');
    expect(paths).toContain('score.json');
    expect(paths).not.toContain('03-mcp-governance/MCP_READINESS.md');
    expect(paths).not.toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
  });

  it('keeps focused ZIP exports aligned with score.json when selected packages are omitted by the caller', async () => {
    const report = buildSampleReport();
    const scoreJson = buildScoreJson(report, { selectedPackages: ['safety-risk'] });
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson, selectedPackages: [] }
    );
    const zip = await JSZip.loadAsync(blob);
    const paths = Object.values(zip.files).filter(file => !file.dir).map(file => file.name).sort();

    expect(paths).toEqual([...scoreJson.generatedFiles].sort());
    expect(paths).toContain('08-security-data/DATA_PRIVACY_CHECKLIST.md');
    expect(paths).toContain('score.json');
    expect(paths).not.toContain('01-agent-instructions/AGENTS.md');
    expect(paths).not.toContain('06-client-handoff/CLIENT_HANDOFF_REPORT.md');
  });

  it('includes at least five SKILL.md files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);
    const skillPaths = getDeliveryPackRequiredPaths().filter(path => path.endsWith('/SKILL.md'));

    expect(skillPaths.length).toBeGreaterThanOrEqual(5);
    for (const path of skillPaths) {
      const content = await zipText(zip, path);
      expect(content.trim()).toContain('Generated by ShipSeal');
      expect(content.trim()).toContain(report.repoName);
    }
  });

  it('exports non-empty eval, red-team, and client handoff files', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      { repositoryName: report.repoName, scoreJson: buildScoreJson(report) }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of [
      '04-testing/EVAL_TEST_CASES.md',
      '04-testing/RED_TEAM_PROMPTS.md',
      '06-client-handoff/CLIENT_HANDOFF_REPORT.md',
    ]) {
      const content = await zipText(zip, path);
      expect(content.trim().length).toBeGreaterThan(80);
      expect(content).toContain('ShipSeal');
      expect(content).toContain(report.repoName);
      expect(content).toContain('Generated by ShipSeal');
    }
  });
});
