import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { buildSampleReport } from '@/lib/readiness';
import {
  READINESS_FIX_PACK_MANIFEST,
  buildReadinessFixPackZipBlob,
  buildReadinessFixPackZipFilename,
  buildSuggestedReadinessFixPack,
} from '@/lib/readinessFixPack';
import { buildReadinessPrPlan } from '@/lib/readinessPr';

describe('Suggested Readiness Fix Pack generator', () => {
  it('defines required manifest entries with score improvement metadata', () => {
    const paths = READINESS_FIX_PACK_MANIFEST.map(file => file.path);

    expect(paths).toContain('AGENTS.md');
    expect(paths).toContain('CLAUDE.md');
    expect(paths).toContain('CONTRIBUTING.md');
    expect(paths).toContain('SECURITY.md');
    expect(paths).toContain('.github/workflows/ci.yml');

    for (const entry of READINESS_FIX_PACK_MANIFEST) {
      expect(entry.readinessCategory).toBeTruthy();
      expect(entry.purpose).toBeTruthy();
      expect(entry.expectedImpact).toContain('Expected to improve future ShipSeal scans');
      expect(typeof entry.isSafeToAdd).toBe('boolean');
      expect(typeof entry.requiresHumanReview).toBe('boolean');
    }
  });

  it('maps suggested files to readiness categories with non-empty previews', () => {
    const pack = buildSuggestedReadinessFixPack(buildSampleReport());
    const paths = pack.map(file => file.path);

    expect(paths).toContain('AGENTS.md');
    expect(paths).toContain('CLAUDE.md');
    expect(paths).toContain('CONTRIBUTING.md');
    expect(paths).toContain('.github/workflows/ci.yml');
    expect(paths).toContain('docs/CRITICAL_FILES_POLICY.md');

    for (const file of pack) {
      expect(file.readinessCategory).toBeTruthy();
      expect(file.purpose).toBeTruthy();
      expect(file.expectedImpact).toBeTruthy();
      expect(file.whyUseful).toBeTruthy();
      expect(file.improves).toBeTruthy();
      expect(file.content).toContain('Generated by ShipSeal');
      expect(file.content.trim().length).toBeGreaterThan(80);
    }
  });

  it('exports a separate non-empty Readiness Fix Pack ZIP', async () => {
    const report = buildSampleReport();
    const filename = buildReadinessFixPackZipFilename(report.repoName);
    const blob = await buildReadinessFixPackZipBlob(report);
    const zip = await JSZip.loadAsync(await readBlob(blob));
    const paths = Object.keys(zip.files).filter(path => !zip.files[path].dir);

    expect(filename).toMatch(/^shipseal-readiness-fix-pack-/);
    expect(paths).toContain('AGENTS.md');
    expect(paths).toContain('CLAUDE.md');
    expect(paths).toContain('CONTRIBUTING.md');
    expect(paths).toContain('SECURITY.md');
    expect(paths).toContain('.github/workflows/ci.yml');

    for (const path of ['AGENTS.md', 'CLAUDE.md', 'CONTRIBUTING.md', 'SECURITY.md', '.github/workflows/ci.yml']) {
      const content = await zip.file(path)?.async('string');
      expect(content?.trim().length).toBeGreaterThan(80);
    }
  });

  it('manual Git steps refer to the Fix Pack branch and commit', () => {
    const plan = buildReadinessPrPlan();

    expect(plan.manualGitSteps).toContain('git checkout -b shipseal/readiness-pack');
    expect(plan.manualGitSteps).toContain('shipseal-readiness-fix-pack-[repo].zip');
    expect(plan.manualGitSteps).toContain('git commit -m "Add ShipSeal readiness fix pack"');
  });
});

function readBlob(blob: Blob): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(reader.error);
    reader.onload = () => resolve(reader.result as ArrayBuffer);
    reader.readAsArrayBuffer(blob);
  });
}
