import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { generateTestingPackFiles } from '@/lib/deliveryPack';
import { normalizeProjectIntake } from '@/lib/intake';
import { buildSampleReport } from '@/lib/readiness';
import {
  buildAgentPackZipBlob,
  buildRepoContextPackJson,
  buildScoreJson,
} from '@/lib/exports';

const CATEGORY_HEADINGS = [
  '## happy path',
  '## edge cases',
  '## hallucination checks',
  '## prompt injection',
  '## privacy/data leakage',
  '## refusal/boundary',
  '## regression',
];

function intake() {
  return normalizeProjectIntake({
    projectName: 'Testing Pack Project',
    appDescription: 'AI workspace for project delivery teams.',
    aiUseCase: 'Generates client-ready delivery summaries.',
    targetUsers: 'Delivery managers',
  }, 'fallback-project');
}

function numberedLineCount(content: string) {
  return content.split('\n').filter(line => /^\d+\.\s+/.test(line.trim())).length;
}

describe('ShipSeal testing pack generator', () => {
  it('generates at least 30 numbered eval test cases', () => {
    const files = generateTestingPackFiles(intake());

    expect(numberedLineCount(files.evalTestCases)).toBeGreaterThanOrEqual(30);
  });

  it('generates at least 10 numbered red-team prompts', () => {
    const files = generateTestingPackFiles(intake());

    expect(numberedLineCount(files.redTeamPrompts)).toBeGreaterThanOrEqual(10);
  });

  it('includes all required category headings', () => {
    const files = generateTestingPackFiles(intake());

    for (const heading of CATEGORY_HEADINGS) {
      expect(files.evalTestCases).toContain(heading);
    }
  });

  it('generates non-empty testing outputs that use intake context', () => {
    const files = generateTestingPackFiles(intake());

    for (const content of Object.values(files)) {
      expect(content.trim().length).toBeGreaterThan(200);
      expect(content).toContain('Generated by ShipSeal');
      expect(content).toContain('Testing Pack Project');
    }

    expect(files.testingStrategy).toContain('AI workspace for project delivery teams.');
    expect(files.testingStrategy).toContain('Generates client-ready delivery summaries.');
  });

  it('exports testing files under the 04-testing folder in the Delivery Pack ZIP', async () => {
    const report = buildSampleReport();
    const blob = await buildAgentPackZipBlob(
      report.agentPack,
      report.mcpReadiness.generatedFiles,
      { markdown: report.contextPack, json: buildRepoContextPackJson(report) },
      {
        repositoryName: report.repoName,
        scoreJson: buildScoreJson(report),
        intake: intake(),
      }
    );
    const zip = await JSZip.loadAsync(blob);

    for (const path of [
      '04-testing/EVAL_TEST_CASES.md',
      '04-testing/RED_TEAM_PROMPTS.md',
      '04-testing/TESTING_STRATEGY.md',
    ]) {
      const file = zip.file(path);
      expect(file, path).toBeTruthy();
      expect((await file!.async('string')).trim().length).toBeGreaterThan(200);
    }
  });
});
