import type { ProjectIntake } from '../intake';

export interface AiActReadinessFiles {
  checklist: string;
  transparencyNotice: string;
  legalReviewQuestions: string;
}

const LEGAL_DISCLAIMER = 'This is not legal advice. Ez nem jogi tanácsadás.';

export function generateAiActReadinessFiles(intake: ProjectIntake): AiActReadinessFiles {
  return {
    checklist: generateAiActChecklist(intake),
    transparencyNotice: generateTransparencyNoticeDraft(intake),
    legalReviewQuestions: generateLegalReviewQuestions(intake),
  };
}

function generateAiActChecklist(intake: ProjectIntake) {
  const warnings = [
    intake.usedInEU && intake.generatesUserFacingContent
      ? '- Transparency warning: EU use with user-facing AI output detected. A transparency notice is recommended before client delivery.'
      : '- Transparency warning: No EU + user-facing AI output combination was indicated in intake.',
    intake.handlesPersonalData
      ? '- Data protection warning: Personal data handling was indicated. GDPR/data protection review may be required.'
      : '- Data protection warning: Personal data handling was not indicated in intake.',
    !intake.hasHumanApproval
      ? '- Human oversight warning: Human approval status was not provided in the intake. Confirm an oversight path before client delivery.'
      : '- Human oversight warning: Human approval was indicated in intake.',
  ];

  return [
    `# AI_ACT_READINESS_CHECKLIST.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    LEGAL_DISCLAIMER,
    '',
    '## Scope',
    'This checklist is a deterministic ShipSeal v1 readiness aid. It does not certify legal compliance or classify the system under the EU AI Act.',
    '',
    '## Intake summary',
    `- Project: ${intake.projectName}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    `- Target users: ${valueOrNotProvided(intake.targetUsers)}`,
    `- AI provider: ${valueOrNotProvided(intake.aiProvider)}`,
    `- Model: ${valueOrNotProvided(intake.modelName)}`,
    `- Used in the EU: ${yesNo(intake.usedInEU)}`,
    `- Handles personal data: ${yesNo(intake.handlesPersonalData)}`,
    `- Generates user-facing AI output: ${yesNo(intake.generatesUserFacingContent)}`,
    `- Human approval before action/publication: ${yesNo(intake.hasHumanApproval)}`,
    '',
    '## Deterministic warnings',
    ...warnings,
    '',
    '## V1 review checklist',
    '- Confirm whether the AI use case is prohibited, high-risk, limited-risk, or minimal-risk with a qualified reviewer.',
    '- Confirm whether the system gives users enough notice that AI is involved.',
    '- Confirm whether generated content can be mistaken for human-authored content.',
    '- Confirm whether personal data, special category data, children, workers, or vulnerable users are involved.',
    '- Confirm logging, escalation, and human oversight responsibilities.',
    '- Confirm provider, model, data retention, and subprocessors before production use.',
    '',
  ].join('\n');
}

function generateTransparencyNoticeDraft(intake: ProjectIntake) {
  return [
    `# TRANSPARENCY_NOTICE_DRAFT.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    LEGAL_DISCLAIMER,
    '',
    '## English disclosure draft',
    `This ${intake.clientName?.trim() ? `service for ${intake.clientName.trim()}` : 'service'} may use AI-assisted functionality in ${intake.projectName}. The AI feature may support: ${valueOrWorkflow(intake.aiUseCase)}. AI-generated or AI-assisted outputs should be reviewed before relying on them for important decisions.`,
    '',
    '## Magyar tájékoztató szövegtervezet',
    `A ${intake.projectName} szolgáltatás AI-támogatott funkciókat használhat. Az AI funkció célja: ${valueOrWorkflow(intake.aiUseCase)}. Az AI által generált vagy támogatott kimeneteket fontos döntések előtt emberi ellenőrzéssel javasolt átnézni.`,
    '',
    '## Intake signals for reviewer',
    `- Used in the EU: ${yesNo(intake.usedInEU)}`,
    `- Generates user-facing AI output: ${yesNo(intake.generatesUserFacingContent)}`,
    `- Handles personal data: ${yesNo(intake.handlesPersonalData)}`,
    `- Human approval before action/publication: ${yesNo(intake.hasHumanApproval)}`,
    `- AI provider/model: ${valueOrNotProvided(intake.aiProvider)} / ${valueOrNotProvided(intake.modelName)}`,
    '',
    '## Publication note',
    'This is a draft disclosure only. Product, privacy, and legal owners should adapt it to the actual user journey, jurisdiction, provider terms, and risk profile.',
    '',
  ].join('\n');
}

function generateLegalReviewQuestions(intake: ProjectIntake) {
  return [
    `# LEGAL_REVIEW_QUESTIONS.md - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    LEGAL_DISCLAIMER,
    '',
    '## Questions for legal or compliance reviewer',
    `1. Based on the AI use case (${valueOrWorkflow(intake.aiUseCase)}), what EU AI Act risk category should be assessed?`,
    `2. If the product is used in the EU (${yesNo(intake.usedInEU)}), which transparency, documentation, and user notice obligations may apply?`,
    `3. If user-facing AI output is generated (${yesNo(intake.generatesUserFacingContent)}), what disclosure wording should be shown and where in the user journey?`,
    `4. If personal data is handled (${yesNo(intake.handlesPersonalData)}), what GDPR lawful basis, DPA, DPIA, retention, and data subject rights review is needed?`,
    `5. Is human approval before action/publication sufficient or missing (${yesNo(intake.hasHumanApproval)}) for the intended use case?`,
    `6. Are target users (${valueOrNotProvided(intake.targetUsers)}) employees, consumers, children, vulnerable groups, or regulated professionals?`,
    `7. Are the selected provider and model (${valueOrNotProvided(intake.aiProvider)} / ${valueOrNotProvided(intake.modelName)}) approved for this data and jurisdiction?`,
    '8. What logs, audit trails, incident response steps, and appeal/escalation paths should be documented before release?',
    '9. What client-facing disclaimers, terms, privacy notices, or contract updates are required before handoff?',
    '10. What residual risks should be accepted by the client in writing before production launch?',
    '',
    '## Reviewer note',
    'ShipSeal does not determine compliance. Use these questions to drive legal, privacy, and compliance review.',
    '',
  ].join('\n');
}

function yesNo(value: boolean) {
  return value ? 'yes' : 'Needs confirmation';
}

function valueOrNotProvided(value?: string) {
  return value?.trim() || 'Not provided';
}

function valueOrWorkflow(value?: string) {
  return value?.trim() || 'the selected workflow';
}
