import type { ProjectIntake } from '../intake';

export interface ClientHandoffFiles {
  clientHandoffReport: string;
  executiveSummary: string;
  nextStepsRoadmap: string;
}

interface HandoffScoreSummary {
  repositoryName: string;
  score: string;
  status: string;
  isReady: boolean | null;
  criticalBlockers: Array<{ title?: string; detail?: string }>;
  improvements: Array<{ title?: string; category?: string; detail?: string }>;
  categories: Array<{ name?: string; earned?: number; max?: number }>;
  generatedFiles: string[];
  packageLabel: string;
  packageSummary: string;
  scanLimited: boolean;
  scanWarnings: string[];
  scanEvidence: {
    sourceType: string;
    repositoryFullName: string;
    branchOrRef: string;
    discoveredFileCount: string;
    analyzedFileCount: string;
    ignoredFileCount: string;
    keyFileSignals: string[];
  };
  mcpStatus: string;
  mcpScore: string;
  aiActSummary: string;
}

const DISCLAIMER = 'Disclaimer: This report is a delivery readiness aid only. This is not legal advice and this is not a production security audit.';

export function generateClientHandoffFiles(intake: ProjectIntake, scoreJson?: unknown): ClientHandoffFiles {
  const summary = parseScoreSummary(scoreJson, intake.projectName);
  const strengths = topStrengths(summary);
  const risks = topRisks(summary, intake);
  const missingDocs = missingDocumentation(summary);
  const testing = testingStatus(summary);
  const goNoGo = goNoGoRecommendation(summary, intake);

  return {
    clientHandoffReport: renderClientHandoffReport(intake, summary, strengths, risks, missingDocs, testing, goNoGo),
    executiveSummary: renderExecutiveSummary(intake, summary, strengths, risks, goNoGo),
    nextStepsRoadmap: renderNextStepsRoadmap(intake, summary, risks, missingDocs),
  };
}

function renderClientHandoffReport(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  strengths: string[],
  risks: string[],
  missingDocs: string[],
  testing: string,
  goNoGo: string
) {
  return [
    `# ShipSeal Client Handoff Report - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Executive summary',
    executiveSummaryParagraph(intake, summary, goNoGo),
    '',
    '## Client and project context',
    `- Project: ${intake.projectName}`,
    `- Client: ${clientAgencyValue(intake.clientName)}`,
    `- Agency: ${clientAgencyValue(intake.agencyName)}`,
    `- App description: ${valueOrNotProvided(intake.appDescription)}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    '',
    '## ShipSeal readiness snapshot',
    `- Repository scanned: ${summary.repositoryName}`,
    `- Selected package: ${summary.packageLabel}`,
    `- Package focus: ${summary.packageSummary}`,
    `- Generated outputs: ${summary.generatedFiles.length}`,
    `- Scan coverage: ${summary.scanLimited ? 'Limited scan' : 'Full scan'}`,
    `- Scan source: ${summary.scanEvidence.sourceType}`,
    `- Branch/ref: ${summary.scanEvidence.branchOrRef}`,
    `- Files discovered/analyzed/ignored: ${summary.scanEvidence.discoveredFileCount} / ${summary.scanEvidence.analyzedFileCount} / ${summary.scanEvidence.ignoredFileCount}`,
    `- Score: ${summary.score}`,
    `- Readiness status: ${summary.status}`,
    `- Critical delivery risks detected: ${summary.criticalBlockers.length}`,
    `- Recommended decision: ${goNoGo}`,
    '',
    ...(summary.scanLimited ? [
      '## Limited scan warning',
      '- ShipSeal could not fully parse the repository ZIP, so this report is based on deterministic fallback data.',
      '- Do not present this output as a complete client handoff audit. Re-run ShipSeal with a valid repository ZIP or GitHub import before relying on the score.',
      ...asBullets(summary.scanWarnings),
      '',
    ] : []),
    '## Scan evidence',
    `- Source archive: ${summary.scanEvidence.sourceType}`,
    `- Repository/ref: ${summary.scanEvidence.repositoryFullName} @ ${summary.scanEvidence.branchOrRef}`,
    `- File coverage: ${summary.scanEvidence.analyzedFileCount} analyzed out of ${summary.scanEvidence.discoveredFileCount} discovered files.`,
    '- Static scan only: ShipSeal read repository structure and key project files without executing code.',
    ...asBullets(summary.scanEvidence.keyFileSignals),
    '',
    ...(missingIntakeNote(intake) ? [
      '## Intake note',
      `- ${missingIntakeNote(intake)}`,
      '',
    ] : []),
    '## What looks ready',
    ...asBullets(strengths),
    '',
    '## Main risks to discuss before handoff',
    ...asBullets(risks),
    '',
    '## Missing or weak documentation signals',
    ...asBullets(missingDocs),
    '',
    '## Testing status for client handoff',
    `- ${testing}`,
    '',
    '## AI Act readiness pre-screen',
    `- ${summary.aiActSummary}`,
    '',
    '## MCP readiness',
    `- MCP status: ${summary.mcpStatus}`,
    `- MCP score: ${summary.mcpScore}`,
    '',
    '## Go / No-Go recommendation',
    `- ${goNoGo}`,
    '- Treat this as a handoff readiness recommendation, not a production launch approval.',
    '',
    '## 30/60/90 day next steps roadmap',
    '### 30 days',
    '- Review this report with the client owner and agree which risks must be fixed before delivery.',
    '- Run the eval and red-team tests with synthetic data and record pass/fail evidence.',
    '- Confirm AI Act, privacy, and transparency notes with the right client-side owner.',
    '',
    '### 60 days',
    '- Close missing documentation items that would slow down future maintenance or AI-assisted work.',
    '- Tighten MCP access boundaries, approval steps, and client operating notes.',
    '- Re-run ShipSeal after remediation and compare score, risks, and handoff readiness.',
    '',
    '### 90 days',
    '- Prepare a production hardening plan with security, privacy, legal, and operations owners where relevant.',
    '- Decide which optional improvements should become recurring delivery standards.',
    '- Establish a simple cadence for refreshing the Delivery Pack as the project changes.',
    '',
  ].join('\n');
}

function renderExecutiveSummary(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  strengths: string[],
  risks: string[],
  goNoGo: string
) {
  return [
    `# ShipSeal Executive Summary - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Summary',
    executiveSummaryParagraph(intake, summary, goNoGo),
    '',
    '## Client context',
    `- Client: ${clientAgencyValue(intake.clientName)}`,
    `- Agency: ${clientAgencyValue(intake.agencyName)}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    '',
    '## What looks strong',
    ...asBullets(strengths.slice(0, 3)),
    '',
    '## What needs client attention',
    ...asBullets(risks.slice(0, 3)),
    '',
    '## Go / No-Go recommendation',
    `- ${goNoGo}`,
    '',
  ].join('\n');
}

function renderNextStepsRoadmap(
  intake: ProjectIntake,
  summary: HandoffScoreSummary,
  risks: string[],
  missingDocs: string[]
) {
  return [
    `# ShipSeal Next Steps Roadmap - ${intake.projectName}`,
    '',
    'Generated by ShipSeal.',
    DISCLAIMER,
    '',
    '## Roadmap basis',
    `- Client: ${clientAgencyValue(intake.clientName)}`,
    `- Agency: ${clientAgencyValue(intake.agencyName)}`,
    `- App description: ${valueOrNotProvided(intake.appDescription)}`,
    `- AI use case: ${valueOrNotProvided(intake.aiUseCase)}`,
    `- Scan coverage: ${summary.scanLimited ? 'Limited scan' : 'Full scan'}`,
    `- ShipSeal score: ${summary.score}`,
    `- Status: ${summary.status}`,
    `- Main risk themes: ${risks.slice(0, 3).join('; ') || 'Not detected'}`,
    '',
    '## 30 days',
    '- Agree the handoff decision with the client owner and document any accepted risks.',
    '- Resolve critical blockers, or document why a blocker is not applicable to this project.',
    '- Run the testing pack eval cases and red-team prompts, then record pass/fail evidence.',
    '- Review missing documentation: ' + (missingDocs.join('; ') || 'Not detected'),
    '',
    '## 60 days',
    '- Convert repeatable checks into CI, release checklists, or documented quality gates.',
    '- Confirm MCP access remains limited, intentional, and approval-gated.',
    '- Update transparency, privacy, and handoff materials after reviewer feedback.',
    '',
    '## 90 days',
    '- Schedule a production security audit if the project is moving toward launch.',
    '- Re-run ShipSeal and compare score, blockers, and readiness changes.',
    '- Finalize client ownership for ongoing Delivery Pack maintenance.',
    '',
  ].join('\n');
}

function executiveSummaryParagraph(intake: ProjectIntake, summary: HandoffScoreSummary, goNoGo: string) {
  const client = intake.clientName?.trim() ? ` for ${intake.clientName.trim()}` : '';
  const appDescription = intake.appDescription?.trim()
    ? `The application is described as: ${intake.appDescription.trim()}`
    : '';

  return [
    `${intake.projectName}${client} was reviewed with ShipSeal to prepare a practical AI project handoff.`,
    `The current score is ${summary.score} and the readiness status is ${summary.status}.`,
    `The recommended handoff decision is: ${goNoGo}`,
    appDescription,
    'Use this report to align the client, delivery team, and reviewers on what is ready, what needs attention, and what should happen next.',
  ].filter(Boolean).join(' ');
}

function missingIntakeNote(intake: ProjectIntake) {
  const missing = [
    ['client', intake.clientName],
    ['agency', intake.agencyName],
    ['app description', intake.appDescription],
    ['AI use case', intake.aiUseCase],
  ].filter(([, value]) => typeof value !== 'string' || !value.trim()).map(([label]) => label);
  const missingClientOrAgency = missing.includes('client') || missing.includes('agency');

  if (!missing.length) return '';
  if (missingClientOrAgency) {
    return `Client and agency fields can be completed before final delivery. Missing project context: ${missing.join(', ')}.`;
  }
  return `Some project context can be completed before final delivery: ${missing.join(', ')}.`;
}

function parseScoreSummary(scoreJson: unknown, fallbackRepositoryName: string): HandoffScoreSummary {
  const source = asRecord(scoreJson);
  const mcp = asRecord(source.mcpReadiness);
  const repoContext = asRecord(source.repoContextPack);
  const scanSummary = asRecord(source.scanSummary);
  const scanEvidence = asRecord(source.scanEvidence);
  const deliveryFocus = asRecord(source.deliveryPackFocus);

  return {
    repositoryName: stringValue(source.repositoryName) || fallbackRepositoryName || 'Not provided',
    score: typeof source.score === 'number' ? `${source.score}/100` : 'Not detected',
    status: stringValue(source.status) || 'Not detected',
    isReady: typeof source.isReady === 'boolean' ? source.isReady : null,
    criticalBlockers: arrayValue(source.criticalBlockers).map(asRecord),
    improvements: arrayValue(source.improvements).map(asRecord),
    categories: arrayValue(source.categories).map(asRecord),
    generatedFiles: arrayValue(source.generatedFiles).map(value => String(value)),
    packageLabel: stringValue(deliveryFocus.packageLabel) || 'Full ShipSeal package',
    packageSummary: stringValue(deliveryFocus.packageSummary) || 'Full ShipSeal outputs prepared.',
    scanLimited: scanSummary.limited === true || stringValue(scanSummary.scanMode) === 'limited-fallback',
    scanWarnings: arrayValue(scanSummary.warnings).map(value => String(value)),
    scanEvidence: {
      sourceType: displayEvidenceSource(stringValue(scanEvidence.sourceType)),
      repositoryFullName: stringValue(scanEvidence.repositoryFullName) || stringValue(source.repositoryName) || fallbackRepositoryName || 'Not provided',
      branchOrRef: stringValue(scanEvidence.branchOrRef) || 'default',
      discoveredFileCount: numberString(scanEvidence.discoveredFileCount),
      analyzedFileCount: numberString(scanEvidence.analyzedFileCount),
      ignoredFileCount: numberString(scanEvidence.ignoredFileCount),
      keyFileSignals: keyFileSignals(asRecord(scanEvidence.keyFilesFound)),
    },
    mcpStatus: stringValue(mcp.status) || stringValue(repoContext.mcpStatus) || 'Not detected',
    mcpScore: typeof mcp.score === 'number' ? `${mcp.score}/100` : 'Not detected',
    aiActSummary: 'Pre-screen only. Review AI Act, transparency, privacy, and human oversight notes with qualified reviewers.',
  };
}

function topStrengths(summary: HandoffScoreSummary) {
  const strengths = summary.categories
    .filter(category => typeof category.earned === 'number' && typeof category.max === 'number' && category.max > 0 && category.earned / category.max >= 0.7)
    .slice(0, 4)
    .map(category => `${stringValue(category.name) || 'Readiness area'} has a strong signal in the scan (${category.earned}/${category.max}).`);

  if (summary.generatedFiles.length) strengths.push(`The ShipSeal Delivery Pack includes ${summary.generatedFiles.length} manifest outputs for review and handoff.`);
  strengths.push(...summary.scanEvidence.keyFileSignals.slice(0, 4));
  if (summary.isReady === true) strengths.push('The scan did not report critical handoff blockers.');

  return strengths.length ? strengths : ['Not detected'];
}

function keyFileSignals(keyFiles: Record<string, unknown>) {
  const signals = [
    keyFiles.readme === true ? 'README found.' : '',
    keyFiles.packageJson === true ? 'package.json found.' : '',
    keyFiles.tests === true ? 'Test files found.' : '',
    keyFiles.ciConfig === true ? 'CI workflow found.' : '',
    keyFiles.envExample === true ? '.env example found.' : '',
    keyFiles.gitignore === true ? '.gitignore found.' : '',
    keyFiles.agentInstructions === true ? 'Agent instruction files found.' : '',
    keyFiles.claudeInstructions === true ? 'CLAUDE.md found.' : '',
  ].filter(Boolean);

  return signals.length ? signals : ['No key project files were confirmed in the scan evidence.'];
}

function displayEvidenceSource(sourceType?: string) {
  if (sourceType === 'github-app') return 'GitHub App';
  if (sourceType === 'public-github') return 'Public GitHub';
  if (sourceType === 'zip') return 'ZIP upload';
  return 'Not provided';
}

function numberString(value: unknown) {
  return typeof value === 'number' ? value.toLocaleString() : 'Not provided';
}

function topRisks(summary: HandoffScoreSummary, intake: ProjectIntake) {
  const risks = summary.criticalBlockers.slice(0, 5).map(blocker => `${stringValue(blocker.title) || 'Critical delivery risk'}: ${stringValue(blocker.detail) || 'Details not provided'}.`);

  if (summary.isReady === false && !risks.length) risks.push('The project is not currently marked ready for client handoff by the ShipSeal readiness rule.');
  if (summary.scanLimited) risks.push('Limited scan warning: ZIP parsing failed, so this output is not a complete client handoff audit.');
  if (intake.handlesPersonalData) risks.push('Personal data handling was indicated. Ask the client owner to confirm privacy/GDPR review before production use.');
  if (intake.usedInEU && intake.generatesUserFacingContent) risks.push('EU use with user-facing AI output was indicated. Review and adapt the transparency notice before client delivery.');
  if (!intake.hasHumanApproval) risks.push('Human approval status was not provided in the intake. Confirm reviewer ownership before relying on AI output for important decisions.');

  return risks.length ? risks : ['No major handoff risks were detected from the available scan and intake data.'];
}

function missingDocumentation(summary: HandoffScoreSummary) {
  const missing = summary.improvements
    .filter(improvement => /README|documentation|CONTRIBUTING|CODEOWNERS|Testing strategy|Deployment|Security/i.test(`${improvement.title || ''} ${improvement.category || ''}`))
    .slice(0, 6)
    .map(improvement => stringValue(improvement.title) || stringValue(improvement.category) || 'Documentation item');

  return missing.length ? missing : ['Not detected'];
}

function testingStatus(summary: HandoffScoreSummary) {
  const quality = summary.categories.find(category => /build|test|quality/i.test(stringValue(category.name) || ''));
  if (quality && typeof quality.earned === 'number' && typeof quality.max === 'number') {
    return `Testing and quality signal: ${quality.earned}/${quality.max}. Use the testing pack before client delivery.`;
  }
  return 'Not detected. Use the testing pack before client delivery.';
}

function goNoGoRecommendation(summary: HandoffScoreSummary, intake: ProjectIntake) {
  if (summary.criticalBlockers.length > 0) return 'No-Go for unsupervised delivery until critical blockers are resolved or formally accepted.';
  if (summary.isReady === true && intake.hasHumanApproval) return 'Go for controlled handoff with documented human approval and standard review.';
  if (summary.isReady === true) return 'Conditional Go for handoff; confirm human approval ownership before production use.';
  return 'Conditional Go for discovery or remediation only; not recommended for production handoff yet.';
}

function asBullets(values: string[]) {
  return values.length ? values.map(value => `- ${value}`) : ['- Not detected'];
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? value as Record<string, unknown> : {};
}

function arrayValue(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function valueOrNotProvided(value?: string) {
  return value?.trim() || 'Not provided';
}

function clientAgencyValue(value?: string) {
  return value?.trim() || 'Can be completed before final delivery';
}
