import { useEffect, useState } from 'react';
import { Nav } from '@/components/agentready/Nav';
import { SurfaceState } from '@/components/agentready/SurfaceState';

type AdminPayload = { overview: Record<string, number | null>; needsAttention: Array<Record<string, unknown>>; recentEvents: Array<Record<string, unknown>>; operation: Record<string, unknown> | null };
export default function Admin() {
  const [data, setData] = useState<AdminPayload | null>(null);
  const [error, setError] = useState(false);
  const [query, setQuery] = useState('');
  const [searched, setSearched] = useState(false);
  useEffect(() => { void load(); }, []);
  async function load(search = '') { try { const response = await fetch(`/api/admin?${search ? `q=${encodeURIComponent(search)}` : ''}`, { credentials: 'include' }); if (!response.ok) throw new Error('unavailable'); setData(await response.json() as AdminPayload); setError(false); } catch { setError(true); } }
  if (error) return <><Nav /><main className="container max-w-5xl py-28"><SurfaceState tone="error" title="Operations surface unavailable" description="This internal surface is restricted or temporarily unavailable." /></main></>;
  if (!data) return <><Nav /><main className="container max-w-5xl py-28"><SurfaceState tone="loading" title="Loading operations" description="Reading safe operational aggregates." /></main></>;
  const metric = (key: string) => data.overview[key] ?? 0;
  return <div className="min-h-screen bg-background"><Nav /><main className="container max-w-7xl pb-20 pt-28"><div className="text-xs font-mono uppercase tracking-wider text-primary">Internal operations</div><h1 className="mt-2 font-display text-3xl font-semibold">ShipSeal Operations</h1><p className="mt-2 text-sm text-muted-foreground">Safe aggregates and timelines. Repository contents and provider payloads are never shown here.</p>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Scans · 24h', 'scans_24h'], ['Successful scans', 'scans_succeeded_24h'], ['AI completed · 24h', 'ai_completed_24h'], ['AI in progress', 'ai_in_progress'], ['Provider calls today', 'provider_calls_today'], ['Provider limit', 'provider_call_limit'], ['GitHub failures', 'github_failures_24h'], ['Stripe events · 24h', 'stripe_events_24h']].map(([label, key]) => <article key={key} className="rounded-2xl border border-border/60 bg-card/60 p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 font-display text-2xl font-semibold">{metric(key)}</div></article>)}</section>
    <section className="mt-8 rounded-2xl border border-border/60 bg-card/50 p-5"><h2 className="font-display text-xl font-semibold">Needs attention</h2>{data.needsAttention.length ? <ul className="mt-3 divide-y divide-border/50">{data.needsAttention.map((item, index) => <li key={index} className="py-3 text-sm"><span className="font-medium">{String(item.public_operation_id || item.operation_kind)}</span><span className="ml-3 text-muted-foreground">{String(item.state)}{item.terminal_failure_category ? ` · ${String(item.terminal_failure_category)}` : ''}</span></li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">No stuck or recently failed operations require attention.</p>}</section>
    <section className="mt-8 rounded-2xl border border-border/60 bg-card/50 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">Operation lookup</h2><p className="mt-1 text-sm text-muted-foreground">Use an exact public operation ID or support reference.</p></div><form className="flex gap-2" onSubmit={event => { event.preventDefault(); setSearched(true); void load(query); }}><input aria-label="Support reference" className="h-10 w-64 rounded-md border border-border bg-background px-3 text-sm" value={query} onChange={event => setQuery(event.target.value)} placeholder="RI-… or aop_…" /><button className="rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground" type="submit">Search</button></form></div>{searched && (data.operation ? <pre className="mt-4 overflow-auto rounded-xl bg-muted/40 p-4 text-xs">{JSON.stringify(data.operation, null, 2)}</pre> : <p className="mt-4 text-sm text-muted-foreground">No matching operation.</p>)}</section>
    <section className="mt-8 rounded-2xl border border-border/60 bg-card/50 p-5"><h2 className="font-display text-xl font-semibold">Recent safe events</h2><ul className="mt-3 divide-y divide-border/50">{data.recentEvents.slice(0, 12).map((event, index) => <li key={index} className="flex flex-wrap gap-x-3 gap-y-1 py-3 text-sm"><span className="font-medium">{String(event.category)}</span><span>{String(event.action)}</span><span className="text-muted-foreground">{String(event.status)}</span><span className="text-muted-foreground">{String(event.created_at)}</span></li>)}</ul></section>
  </main></div>;
}
