import type { ReadinessReport } from '../types';
import { READINESS_FIX_PACK_MANIFEST } from './manifest';
import type { ReadinessFixPackFile, ReadinessFixPackManifestEntry } from './types';

export function buildSuggestedReadinessFixPack(report: ReadinessReport): ReadinessFixPackFile[] {
  const deliveryPackPaths = new Set([
    ...report.agentPack.map(file => file.name),
    ...report.mcpReadiness.generatedFiles.map(file => file.filename),
    '01-agent-instructions/AGENTS.md',
    '01-agent-instructions/CLAUDE.md',
    '04-testing/CI_QUALITY_GATE.yml',
    '06-client-handoff/CLIENT_HANDOFF_REPORT.md',
  ]);

  return READINESS_FIX_PACK_MANIFEST.map(entry => ({
    ...entry,
    improves: entry.purpose,
    whyUseful: entry.purpose,
    alreadyInDeliveryPack: deliveryPackPaths.has(entry.path) || deliveryPackPaths.has(entry.path.split('/').pop() || entry.path),
    content: buildReadinessFixPackFileContent(report, entry),
  }));
}

export function buildReadinessFixPackFileContent(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  switch (entry.path) {
    case 'AGENTS.md':
      return agentInstructions(report, entry, 'AGENTS.md');
    case 'CLAUDE.md':
      return agentInstructions(report, entry, 'CLAUDE.md');
    case 'CONTRIBUTING.md':
      return contributing(report, entry);
    case 'SECURITY.md':
      return security(report, entry);
    case 'docs/CRITICAL_FILES_POLICY.md':
      return criticalFilesPolicy(report, entry);
    case 'docs/RELEASE_CHECKLIST.md':
      return releaseChecklist(report, entry);
    case 'docs/OWNERSHIP.md':
      return ownership(report, entry);
    case 'docs/shipseal/CI_QUALITY_GATE.example.yml':
      return ciWorkflow(report, true);
    case 'docs/AGENT_CHANGE_POLICY.md':
      return agentChangePolicy(report, entry);
    case 'docs/HANDOFF_CHECKLIST.md':
      return handoffChecklist(report, entry);
    case 'docs/AI_ACT_READINESS_NOTES.md':
      return aiActReadinessNotes(report, entry);
    default:
      return genericMarkdown(report, entry);
  }
}

function agentInstructions(report: ReadinessReport, entry: ReadinessFixPackManifestEntry, title: string) {
  return markdown(report, entry, [
    `# ${title}`,
    '',
    `Repository: ${report.repoName}`,
    `Detected stack: ${stackLabel(report)}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## How AI Coding Agents Should Work Here',
    '',
    '- Read this file and the repository README before editing.',
    '- Prefer small, reviewable changes.',
    '- Do not execute unknown scripts or uploaded code outside the normal project commands.',
    '- Keep business logic, export structure and scanner behavior stable unless the task explicitly asks for changes.',
    '- Explain assumptions and verification results in the final handoff.',
    '',
    '## Recommended Commands',
    '',
    commandList(report),
    '',
    '## Files Requiring Human Review',
    '',
    '- Authentication, payment, security, legal, compliance and data handling code.',
    '- CI/CD, deployment, production configuration and environment variable handling.',
    '- Scanner limits, export manifests, generated report templates and client-facing claims.',
    '',
    '## Delivery Pack Validation',
    '',
    '- Run the ShipSeal scan after repository changes.',
    '- Download the ShipSeal Delivery Pack and confirm reports, tests, AI Act readiness notes and score.json are present.',
    '- Use this Readiness Fix Pack to improve future scans, not as a replacement for human review.',
  ]);
}

function contributing(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# CONTRIBUTING.md',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Contribution Workflow',
    '',
    '1. Create a topic branch for every change.',
    '2. Keep changes small and focused.',
    '3. Run the available verification commands before opening a pull request.',
    '4. Include a short summary, risk notes and test results in the PR description.',
    '5. Ask for human review before merging AI-assisted changes.',
    '',
    '## Verification Commands',
    '',
    commandList(report),
    '',
    '## AI-Assisted Contributions',
    '',
    '- AI-generated changes must be reviewed by a human maintainer.',
    '- Do not let agents modify secrets, production config, payment/auth flows or legal/compliance language without explicit review.',
    '- Include ShipSeal score and Delivery Pack observations when the change affects handoff readiness.',
  ]);
}

function security(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# SECURITY.md',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Security Scope',
    '',
    'This file documents baseline security expectations for repository work and AI-assisted development. It is not a production security audit.',
    '',
    '## Secret Handling',
    '',
    '- Never commit `.env`, API keys, credentials, tokens or private certificates.',
    '- Use `.env.example` for non-sensitive configuration examples.',
    '- Rotate any credential that may have been exposed.',
    '- Treat AI tool prompts and generated context packs as potentially sensitive if they include client or project details.',
    '',
    '## Reporting',
    '',
    '- Report suspected vulnerabilities to the repository owner or designated security reviewer.',
    '- Do not disclose security issues publicly before review.',
    '',
    '## ShipSeal Validation',
    '',
    '- Re-run ShipSeal after security-related repository changes.',
    '- Review security findings, ignored files and secret-handling warnings before client handoff.',
  ]);
}

function criticalFilesPolicy(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# Critical Files Policy',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Files That Need Human Review',
    '',
    '- Authentication, authorization and session handling.',
    '- Payment, billing and subscription code.',
    '- Production deployment, CI/CD and infrastructure configuration.',
    '- Environment variable, secret and credential handling.',
    '- Legal, AI Act, privacy, security and client-facing claims.',
    '- ShipSeal export manifests, client reports and generated handoff templates.',
    '',
    '## Agent Rules',
    '',
    '- Agents may suggest changes to critical files, but should not merge them without human approval.',
    '- Agents should explain risk, test coverage and rollback considerations.',
    '- If a change affects users, data, compliance or production behavior, escalate for review.',
  ]);
}

function releaseChecklist(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# Release Checklist',
    '',
    `Repository: ${report.repoName}`,
    `Detected stack: ${stackLabel(report)}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Before Release',
    '',
    '- [ ] Run install/build/test commands.',
    '- [ ] Confirm no secrets or private credentials are committed.',
    '- [ ] Re-run ShipSeal scan.',
    '- [ ] Download the ShipSeal Delivery Pack.',
    '- [ ] Review CLIENT_HANDOFF_REPORT.md and CLIENT_HANDOFF_REPORT.html.',
    '- [ ] Review AI Act readiness notes and transparency notice draft where relevant.',
    '- [ ] Confirm red-team prompts and eval tests are present.',
    '- [ ] Confirm human review for critical files.',
    '',
    '## Commands',
    '',
    commandList(report),
  ]);
}

function ownership(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# Ownership and Review Routing',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Suggested Review Areas',
    '',
    '- Product owner: client-facing behavior, handoff language and next steps.',
    '- Engineering owner: code quality, architecture, tests and build stability.',
    '- Security reviewer: secret handling, auth/payment/data risks and deployment changes.',
    '- AI governance reviewer: AI use case, transparency, human oversight and AI Act readiness notes.',
    '',
    '## Handoff Rule',
    '',
    'No client handoff should rely only on generated content. ShipSeal output should be reviewed and adjusted by responsible humans before delivery.',
  ]);
}

function agentChangePolicy(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# Agent Change Policy',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Agents May Usually Change',
    '',
    '- Documentation, tests and small UI copy changes.',
    '- Non-production helper scripts and deterministic generated templates.',
    '- Narrow bug fixes with clear verification.',
    '',
    '## Agents Need Human Approval For',
    '',
    '- Security, privacy, legal, compliance or AI Act claims.',
    '- Auth, payment, deployment, database and production configuration.',
    '- Scanner scoring, export contracts and generated client report claims.',
  ]);
}

function handoffChecklist(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# Handoff Checklist',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Client Handoff Review',
    '',
    '- [ ] ShipSeal score and go/no-go status reviewed.',
    '- [ ] Critical risks explained in client-friendly language.',
    '- [ ] Delivery Pack ZIP downloaded and checked.',
    '- [ ] HTML/PDF client report reviewed before sharing.',
    '- [ ] AI Act readiness notes reviewed by the appropriate expert where relevant.',
    '- [ ] Testing and red-team prompts reviewed.',
    '- [ ] Next steps roadmap agreed with the client.',
  ]);
}

function aiActReadinessNotes(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    '# AI Act Readiness Notes',
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    '## Important Disclaimer',
    '',
    'This is not legal advice. Ez nem jogi tanácsadás.',
    '',
    '## Preliminary Technical Notes',
    '',
    '- Document the AI use case, target users and whether outputs are user-facing.',
    '- Document whether the system is used in the EU.',
    '- Document whether personal data may be handled.',
    '- Document whether human review or escalation exists.',
    '- Review transparency notice needs before client handoff.',
    '',
    '## ShipSeal Usage',
    '',
    'Use the ShipSeal Delivery Pack AI Act readiness files as preliminary product-side input for legal or compliance review.',
  ]);
}

function ciWorkflow(report: ReadinessReport, isExample = false) {
  const install = installCommand(report);
  const test = commandFor(report, 'test') || 'npm test';
  const build = commandFor(report, 'build') || 'npm run build';
  const lint = commandFor(report, 'lint');

  return [
    ...(isExample ? [
      '# ShipSeal CI quality gate example',
      '# Documentation only: review before copying this file into .github/workflows/ci.yml.',
      '',
    ] : []),
    'name: ShipSeal Readiness CI',
    '# Generated by ShipSeal',
    '# Review before enabling in production.',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    '    branches: [main]',
    '',
    'jobs:',
    '  quality-gate:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '',
    '      - name: Setup Node',
    '        uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 20',
    '          cache: npm',
    '',
    '      - name: Install dependencies',
    `        run: ${install}`,
    '',
    '      - name: Run tests',
    `        run: ${test}`,
    '',
    ...(lint ? ['      - name: Run lint', `        run: ${lint}`, ''] : []),
    '      - name: Run build',
    `        run: ${build}`,
  ].join('\n');
}

function genericMarkdown(report: ReadinessReport, entry: ReadinessFixPackManifestEntry) {
  return markdown(report, entry, [
    `# ${entry.title}`,
    '',
    `Repository: ${report.repoName}`,
    'Generated by ShipSeal as part of the Readiness Fix Pack.',
    '',
    `## Purpose`,
    '',
    entry.purpose,
    '',
    `## Readiness Category`,
    '',
    entry.readinessCategory,
    '',
    `## Expected Impact`,
    '',
    entry.expectedImpact,
  ]);
}

function markdown(report: ReadinessReport, entry: ReadinessFixPackManifestEntry, lines: string[]) {
  return [
    ...lines,
    '',
    '## Fix Pack Metadata',
    '',
    `- Readiness category: ${entry.readinessCategory}`,
    `- Expected impact: ${entry.expectedImpact}`,
    `- Safe to add automatically: ${entry.isSafeToAdd ? 'yes, after review' : 'no'}`,
    `- Requires human review: ${entry.requiresHumanReview ? 'yes' : 'no'}`,
    `- Stack: ${stackLabel(report)}`,
    '',
    'Generated by ShipSeal.',
  ].join('\n');
}

function stackLabel(report: ReadinessReport) {
  return report.stack.primary || report.summary.detectedStack || 'Not detected';
}

function commandList(report: ReadinessReport) {
  const commands = recommendedCommands(report);
  if (!commands.length) return '- No build/test/lint commands were detected. Add project-specific commands before relying on this checklist.';
  return commands.map(command => `- \`${command}\``).join('\n');
}

function recommendedCommands(report: ReadinessReport) {
  const commands = [
    installCommand(report),
    commandFor(report, 'lint'),
    commandFor(report, 'test'),
    commandFor(report, 'build'),
  ].filter(Boolean) as string[];

  return [...new Set(commands)];
}

function installCommand(report: ReadinessReport) {
  const manager = report.summary.packageManager || report.stack.packageManagers[0] || 'npm';
  if (manager === 'pnpm') return 'pnpm install';
  if (manager === 'yarn') return 'yarn install';
  if (manager === 'bun') return 'bun install';
  return 'npm install';
}

function commandFor(report: ReadinessReport, scriptName: string) {
  if (!report.stack.scripts?.[scriptName]) return '';
  const manager = report.summary.packageManager || report.stack.packageManagers[0] || 'npm';
  if (manager === 'pnpm') return `pnpm ${scriptName}`;
  if (manager === 'yarn') return `yarn ${scriptName}`;
  if (manager === 'bun') return `bun run ${scriptName}`;
  return `npm run ${scriptName}`;
}
