import type { ReadinessFixPackManifestEntry } from './types';

const EXPECTED_IMPACT = 'Expected to improve future ShipSeal scans after human review.';

export const READINESS_FIX_PACK_MANIFEST: ReadinessFixPackManifestEntry[] = [
  {
    path: 'AGENTS.md',
    title: 'Agent operating instructions',
    purpose: 'Define how AI coding agents should work in this repository, including commands, boundaries and review expectations.',
    readinessCategory: 'AI agent instruction readiness',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'CLAUDE.md',
    title: 'Claude agent instructions',
    purpose: 'Give Claude and similar coding agents project-specific context, safe workflow rules and verification commands.',
    readinessCategory: 'AI agent instruction readiness',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'CONTRIBUTING.md',
    title: 'Contribution workflow',
    purpose: 'Document how contributors and AI agents should propose, test and review changes before handoff.',
    readinessCategory: 'Team workflow & governance',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'SECURITY.md',
    title: 'Security and secret handling',
    purpose: 'Document security reporting, secret handling rules and safe repository scanning expectations.',
    readinessCategory: 'Security & secret handling',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/CRITICAL_FILES_POLICY.md',
    title: 'Critical files policy',
    purpose: 'Identify files and folders that require human review before AI-assisted changes are accepted.',
    readinessCategory: 'Team workflow & governance / safety',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/RELEASE_CHECKLIST.md',
    title: 'Release checklist',
    purpose: 'Provide repeatable build, test, scan, Delivery Pack and client handoff checks before release.',
    readinessCategory: 'Build, test & quality gates',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/OWNERSHIP.md',
    title: 'Ownership and review routing',
    purpose: 'Clarify who should review product, engineering, security, AI governance and client handoff changes.',
    readinessCategory: 'Team workflow & governance',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: '.github/workflows/ci.yml',
    title: 'CI quality gate workflow',
    purpose: 'Add a simple GitHub Actions quality gate for install, tests and build commands.',
    readinessCategory: 'Build, test & quality gates',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/AGENT_CHANGE_POLICY.md',
    title: 'Agent change policy',
    purpose: 'Define what AI coding agents can change independently and what must be escalated for approval.',
    readinessCategory: 'AI agent instruction readiness / safety',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/HANDOFF_CHECKLIST.md',
    title: 'Client handoff checklist',
    purpose: 'Track the minimum client-facing review items before an AI project is handed over.',
    readinessCategory: 'Client handoff quality',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
  {
    path: 'docs/AI_ACT_READINESS_NOTES.md',
    title: 'AI Act readiness notes',
    purpose: 'Capture preliminary technical and product-side AI Act readiness notes for expert review.',
    readinessCategory: 'AI Act readiness / governance',
    expectedImpact: EXPECTED_IMPACT,
    isSafeToAdd: true,
    requiresHumanReview: true,
  },
];
